version: "3.8"

services:
  # NEXT.JS APP
  web:
    build:
      context: ${WEB_CONTEXT}
      dockerfile: ${WEB_DOCKERFILE}
    environment:
      NODE_ENV: ${NODE_ENV}
      WORDPRESS_URL: ${WORDPRESS_URL}
      PORT: ${WEB_PORT}
      VIRTUAL_HOST: ${WEB_DOMAIN}
      LETSENCRYPT_HOST: ${WEB_DOMAIN}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    expose:
      - "${WEB_PORT}"
    depends_on:
      - wordpress
    networks:
      - app_network

  # WORDPRESS CMS
  wordpress:
    build:
      context: ${WP_CONTEXT}
      dockerfile: ${WP_DOCKERFILE}
    environment:
      WORDPRESS_DB_HOST: ${WP_DB_HOST}
      WORDPRESS_DB_USER: ${WP_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WP_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WP_DB_NAME}
      VIRTUAL_HOST: ${WP_SUBDOMAIN}
      LETSENCRYPT_HOST: ${WP_SUBDOMAIN}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    volumes:
      - wordpress_data:/var/www/html
    expose:
      - "80"
    depends_on:
      - db
    networks:
      - app_network

  # MYSQL DATABASE
  db:
    image: ${DB_IMAGE}
    command: ${DB_COMMAND}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    networks:
      - app_network

  # Dockerized NGINX (reverse proxy + LetsEncrypt)
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx_certs:/etc/nginx/certs
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
    networks:
      - app_network

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    environment:
      NGINX_PROXY_CONTAINER: nginx-proxy
      DEFAULT_EMAIL: ${LETSENCRYPT_EMAIL}
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx_certs:/etc/nginx/certs
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
    depends_on:
      - nginx-proxy
    networks:
      - app_network

volumes:
  wordpress_data:
  db_data:
  nginx_certs:
  nginx_vhost:
  nginx_html:

networks:
  app_network:
    driver: bridge
